Carsify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import CarsifyApp.urls
from CarsifyApp.views import *
from django.conf.urls import url
from allauth.account.views import LoginView
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from allauth.socialaccount.providers.google.provider import GoogleProvider

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(CarsifyApp.urls, namespace='CarsifyApp')),
    # path('accounts/', include('allauth.urls')),
    # url(r'^login/', LoginView, name="google_login" ),
    # url(r'^signup/', Signup, name="Signup" ),

]+default_urlpatterns(GoogleProvider)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = "Carsify.in"

CarsifyApp/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
app_name = "CarsifyApp"

urlpatterns = [
    path('', Index, name='Index'),

    #Dealer login
    path('dealerapplication/', DealerApplicationView, name='DealerApplication'),

    # Login
    # path('login/', Login_Signup, name='LoginSignup'),
    path('logout/', Logout, name='Logout'),
    path('mailOTP/', MailOTP, name='MailOTP'),
    path('checkOTP/', CheckOTP, name='CheckOTP'),
    # path('signup/', Signup, name='Signup'),
    #dashboard
    path('dashboard/', Dashboard, name='Dashboard'),

    path('addcar/', Addcar, name='Addcar'),
    path('addcarsuccess/', Addcarsuccess, name='Addcarsuccess'),

    #addcardadvaceux
    path('cars-json', json_Car_add, name='cars-json'),
    path('addcar/models-json/<str:car>', json_Car_model, name='models-json'),

    #profile
    path('profile/', Profile, name='Profile'),
    path('editprofile/', Editprofile, name='Editprofile'),

    #filterdata
    path('filter-data', filter_data, name='filter_data'),

    path('myvehicle/', MYvehicle, name='MYvehicle'),

    #vehicle status
    path('editvehicle/<int:cid>', Edit_Vehicle_Details, name='Edit_Vehicle_Details'),
    path('editvehicleimage/<int:cid>', Edit_Vehicle_Images, name='Edit_Vehicle_Images'),
    path('deletevehicleimage/', Delete_Vehicle_Image, name='Delete_Vehicle_Image'),
    path('disable/<int:cid>', Disable_My_Vehicle, name='Disable_My_Vehicle'),
    path('enable/<int:cid>', Enable_My_Vehicle, name='Enable_My_Vehicle'),
    
    #path('deletemycar/<int:cid>', Delete_My_Car, name='Delete_My_Car'),


    path('viewdetails/<int:cid>', Viewdetails, name='Viewdetails'),
    path('mailimages/<int:cid>', MailImages, name='MailImages'),
    path('downloadimages/<int:cid>', DownloadImages, name='DownloadImages'),
    path('favourites/', Favourites, name='Favourites'),
    path('delete_from_favourite/<int:cid>', Delete_From_Favourite, name='Delete_From_Favourite'),
    path('add_favourite_car/<int:cid>',Add_to_Favourite, name='Add_to_Favourite'),
    path('getImage/<int:id>/', GetImages, name="GetImages"),

    url(r'^login/', Login_Signup, name="LoginSignup" ),
    url(r'^signup/', Signup, name="Signup" )
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CarsifyApp/forms.py
from allauth.account.forms import SignupForm
from django import forms
from .models import UserProfile

class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')
    email = forms.EmailField(max_length=30,label='Email')
    def signup(self, request, user):
        user.first_name = self.cleaned_data['firstName']
        user.last_name=self.cleaned_data['last_name']
        user.username=self.cleaned_data['email']
        user.email=self.cleaned_data['email']
        user.save()
        return user

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('user','ProfileImg','ContactNo','Address','Email','AddharNumber','PanNumber','VoterID')

CarsifyApp/views.py
from django.db.models.base import Model
from django.db.models.query import RawQuerySet
from django.shortcuts import render, redirect
from django.views.decorators import csrf
from .models import *
from django.contrib.auth.models import User
from django.core.mail import send_mail, EmailMultiAlternatives
from django.contrib.auth import login, logout, authenticate
from django.http import JsonResponse, HttpResponse
from django.template.loader import render_to_string
from django.db.models import Min,Max,Q
from django.views.decorators.csrf import csrf_exempt
import datetime
from django.core.mail import EmailMultiAlternatives
import cv2
import numpy as np
from zipfile import ZipFile
import os
from os.path import basename
from wsgiref.util import FileWrapper
import random
from django.core.paginator import Paginator
from django.contrib.auth.hashers import check_password

# Create your views here.
def Index(request):
    News = False
    Con = False

    if request.method == 'POST':
        try:
            response = request.POST['nemail']
            Newsletter.objects.create(Email=response)
            News = True
            Con = False
            print(response)
            #send mail

        except:

            Name = request.POST['name']
            Phone = request.POST['number']
            City = request.POST['city']
            State = request.POST['state']
            Query = request.POST['query']
            Remark = request.POST['remark']
            Con = True
            News = False

            Contact.objects.create(Name = Name, Phone = Phone, City = City,  State = State,  Query = Query,  Remark= Remark)

            #send mail

    d = {"News": News, "Con": Con}

    return render(request, 'index.html', d)





'''
def Login_Signup(request):
    error = False
    allready = False
    if request.method == 'POST':
        x = request.POST
        try:
            us = x['usr']
            pa = x['pas']
            user = authenticate(username=us, password=pa)

            if user:
                login(request, user)
                print("login")
                return redirect('CarsifyApp:Dashboard')
            else:
                error = True

        except:
            fullname = x['name']
            email = x['email']
            number = x['number']
            password = x['password']

            data = User.objects.filter(user=email)
            if(data):
                allready = True
            else:
                #create new user
                fname = fullname.split()
                User.objects.create_user(username=email, email=email, first_name=fname[0], last_name=fname[1], password=password)

    d = {"error": error, "allready":allready}
    return render(request, 'login.html', d)
'''

def Login_Signup(request):
    error = False
    not_exist = False
    if request.method == 'POST':
        x = request.POST

        us = x['usr']
        pa = x['pas']
        user = authenticate(username=us, password=pa)
        data = User.objects.filter(username=us)
        Pro = UserProfile.objects.get(user = user)
        if user:
            login(request, user)
            if Pro.isDealer:
                print("Dealer")
            else:
                return redirect('CarsifyApp:Dashboard')

        else:
            if data:
                error = True
            else:
                not_exist=True

    d = {"error": error, "not_exist": not_exist}
    return render(request, 'login.html', d)

def Signup(request):
    allready = False
    if request.method == 'POST':
        x = request.POST
        print(x)
        fullname = x.get('name')
        email = x.get('email')
        number = x.get('number')
        password = x.get('password')

        data = User.objects.filter(username=email)
        if (data):
            allready = True
        else:
            # create new user
            fname = fullname.split()
            if len(fname) >= 2:
                fname = fname
            else:
                fname.append(' ')

            user = User.objects.create_user(username=email, email=email, first_name=fname[0], last_name=fname[1],
                                     password=password)
            UserProfile.objects.create(user=user, ContactNo=number, Email=email)

            type = Address_Type.objects.all()
            for i in type:
                Address.objects.create(user=user, Address_Typee=i)

        return redirect('CarsifyApp:LoginSignup')
    return render(request,'login.html')


def Logout(request):
    logout(request)
    return redirect('CarsifyApp:LoginSignup')


from django.contrib.auth.decorators import login_required

@login_required(login_url='CarsifyApp:LoginSignup')
def Dashboard(request):

    car_data = Individual_Car_Details.objects.filter(Car_Status=False)
    car_company_data = Car_Company.objects.all()
    fuels = Car_Fuel.objects.all()
    transmission_type = Transmission_Type.objects.all()
    states = India_States.objects.all()
    owners = Number_of_Owners.objects.all()
    Body_Types = Car_Body_Type.objects.all()
    minmaxPrice = Individual_Car_Details.objects.aggregate(Min('Price'), Max('Price'))
    minmaxYear = Individual_Car_Details.objects.aggregate(Min('Date_of_Manufacturing'), Max('Date_of_Manufacturing'))
    minmaxKm = Individual_Car_Details.objects.aggregate(Min('KM'), Max('KM'))
    states = India_States.objects.all()
    Companies = Car_Company.objects.values()
    models = Car_Model.objects.values()
    fav_ids = []

    for i in UserFavouriteCars.objects.filter(user=request.user).values():
        fav_ids.append(i.get('carid_id'))

    if request.GET:
        if 'q' in request.GET:
            q = request.GET['q']
            ids=[]
            models_list = []
            #searchdata  by company
            companyData = Companies.filter(Car_Company_Name__icontains =q)
            carmodels = models.filter(Car_Model_Name__icontains = q)
            for data in companyData:
                ids.append(data.get('id'))
            for data in carmodels:
                models_list.append(data.get('Car_Model_Name'))
            car_data = Individual_Car_Details.objects.filter(Q(Company_id__in=ids) | Q(Model__Car_Model_Name__in = models_list )).order_by('-id')
            if(q.strip()==""):
                print("A")
                car_data = Individual_Car_Details.objects.filter(Car_Status=False)

            car_data = car_data.filter(Car_Status=False)
    
    paginator = Paginator(car_data, 9)
    page_number = request.GET.get('page')
    car_data = paginator.get_page(page_number)

    dic = {'car_data': car_data, 'car_company_data': car_company_data, \
           'fuels':fuels,'transmission_type':transmission_type,'owners':owners, \
           'car_body_types':Body_Types, 'Minmaxprice':minmaxPrice, 'minmaxYear': minmaxYear, \
               'minmaxKm': minmaxKm, 'states':states,'fav_id':fav_ids, 'states':states }

    return render(request, 'dashboard.html', dic)



@login_required(login_url='CarsifyApp:LoginSignup')
#filter data
def filter_data(request):
    car_company = request.GET.getlist('company_of_car[]')
    fuel = request.GET.getlist('fuel[]')
    transmission_type = request.GET.getlist('transmission[]')
    owners = request.GET.getlist('owner[]')
    car_body_type = request.GET.getlist('car_body_type[]')
    car_state = request.GET.getlist('state[]')

    try:
        minPrice = request.GET['minPrice']
    except:
        minPrice = 0

    try:
        maxPrice = request.GET['maxPrice']
    except:
        maxPrice = 10000000

    try:
        minYear = request.GET['minYear']
    except:
        minYear = 2000

    try:
        maxYear = request.GET['maxYear']
    except:
        maxYear = 3000

    try:
        minKm = request.GET['minKm']
    except:
        minKm =0

    try:
        maxKm = request.GET['maxKm']
    except:
        maxKm = 1000000




    car_data = Individual_Car_Details.objects.filter(Car_Status=False)
    #sort
    sort = request.GET['orderby']

    if sort=="price+":
        car_data = car_data.order_by('-Price')
        # car_data = request.GET.get('sort','-Price')

    elif sort == "price-":
        car_data = car_data.order_by('Price')

    elif sort == "year+":
        car_data = car_data.order_by('-Date_of_Manufacturing')
    elif sort == "year-":
        car_data = car_data.order_by('Date_of_Manufacturing')

    #price
    car_data = car_data.filter(Price__gte=minPrice)
    car_data = car_data.filter(Price__lte=maxPrice)

    #Km
    car_data = car_data.filter(KM__gte= minKm)
    car_data = car_data.filter(KM__lte= maxKm)

    #Year
    minYeardate = datetime.date(int(minYear), 1, 1)
    maxYeardate = datetime.date(int(maxYear), 12, 31)
    print(minYeardate, maxYeardate)
    car_data = car_data.filter(Date_of_Manufacturing__gte= minYeardate)
    car_data = car_data.filter(Date_of_Manufacturing__lte= maxYeardate)



    #filters
    if len(car_company) > 0:
        car_data = car_data.filter(Company__id__in=car_company).distinct()

    if len(fuel) > 0:
        car_data = car_data.filter(Fuel_Type__id__in=fuel).distinct()

    if len(transmission_type) > 0:
        car_data = car_data.filter(Transmission__id__in=transmission_type).distinct()

    if len(owners) > 0:
        car_data = car_data.filter(Owners__id__in=owners).distinct()

    if len(car_body_type) > 0:
        car_data = car_data.filter(Body_Type__id__in=car_body_type).distinct()

    if len(car_state) > 0:
        car_data = car_data.filter(Registration_State__id__in=car_state).distinct()

    paginator = Paginator(car_data, 9)
    page_number = request.GET.get('page')
    car_data = paginator.get_page(page_number)
    
    t = render_to_string('allcarlist.html', {'car_data': car_data})
    return JsonResponse({'data':t})


def Addcarsuccess(request):
    return render(request, 'addcarsuccess.html')





def resize_img(img_path, img_name):
    pic=cv2.imread(img_path)

    # canvas_size=(333,500)

CarsifyApp/templates/allcarlist.html
{% load static %} {% for car in car_data %}
<div class="col-lg-4 col-md-6 col-12 p-lg-3">
  <div class="cards">
    <div class="row">
      <div class="col-9">{{ car.Company.Car_Company_Name }}</div>
      <div class="col-3">
        <p class="float-right">{{ car.Date_of_Manufacturing.year }}</p>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="card-pic" class="col-12">
          <img src="{{ car.Showimage.url }}" />
        </div>
      </div>
    </div>
    <div class="row py-2">
      <div class="col-8 car-modal">
        <i class="fa fa-car"></i>{{ car.Model.Car_Model_Name}} -
        {{car.Car_Varient }}
      </div>
      <div class="col-4">
        <p class="float-right">
          <i class="fa fa-plus"> </i> {{ car.Owners.Owners }}
        </p>
      </div>
    </div>
    <div class="row py-2">
      <div class="col-6 car-modal">{{ car.City }}</div>
      <div class="col-6">
        <p class="float-right car-number">{{ car.Card_Registration_Number }}</p>
      </div>
    </div>
    <h5>Rs. {{ car.Price }}</h5>
    <div style="box-sizing: border-box" class="car-button">
      <div class="btn-car">
        <a href="{% url 'CarsifyApp:Viewdetails' car.id %}"
          ><button>View Details</button></a
        >
      </div>
      {% if car.id in fav_id %}
      <div
        class="heart-car RemFavHeart text-primary"
        data-page="{{currPage}}"
        data-cid="{{car.id}}"
        style="cursor: pointer"
      >
        <a title="Remove from Favourites"><i class="fa fa-heart"></i></a>
      </div>
      {% else %}
      <div
        class="heart-car AddFavHeart"
        data-page="{{currPage}}"
        data-cid="{{car.id}}"
        style="cursor: pointer"
      >
        <a title="Add to Favourites"><i class="far fa-heart"></i></a>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endfor %}

<script>
  $(".AddFavHeart").click(function () {
    var carid = $(this).attr("data-cid");
    var page = $(this).attr("data-page");
    $.ajax({
      type: "GET",
      url: "/add_favourite_car/" + carid,
      dataType: "json",
      data: {
        p: page,
      },
      success: function (res) {
        $("#filteredcars").html(res.data);
      },
    });
  });

  $(".RemFavHeart").click(function () {
    var carid = $(this).attr("data-cid");
    var page = $(this).attr("data-page");
    $.ajax({
      type: "GET",
      url: "/delete_from_favourite/" + carid,
      dataType: "json",
      data: {
        p: page,
      },
      success: function (res) {
        $("#filteredcars").html(res.data);
      },
    });
  });
</script>

CarsifyApp/templates/dashboardcaraousel.html
{% load static %}
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{{data.0.Image.url}}" class="d-block w-100" alt="...">
      </div>
      {% if data|length != 1 %}
      {% for image in data %}
      {% if image != data|first %}
      <div class="carousel-item">
        <img src="{{image.Image.url}}" class="d-block w-100" alt="...">
      </div>
      {% endif %}
        {% endfor %}
        {% endif %}
    </div>
    {% if data|length != 1 %}
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    {% endif %}
  </div>

CarsifyApp/templates/viewdetails.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/stylesheets/viewdetails.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/stylesheets/navigation.css' %}"
    />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
      integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
      crossorigin="anonymous"
    />
    <link
      rel="shortcut icon"
      href="{% static 'assets/images/favicon.png' %}"
      type="image/.png"
    />
    <title>View Details</title>
  </head>
  <body>
    <!--  navigation  -->
    <nav>
      <div class="menuicon">
        <span class="fas fa-bars"></span>
      </div>
      <div class="logoo">
        <img src="{% static 'assets/images/logo7.png' %}" />
      </div>
      <div class="navitems">
        <li><a href="{% url 'CarsifyApp:Dashboard' %}">Home</a></li>
        <li>
          <a href="#">
            <div class="dropdown show">
              <a
                class="btn dropdown-toggle dropdown-navi"
                href="#"
                role="button"
                id="dropdownMenuLink"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                Booking Management
              </a>

              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="{% url 'CarsifyApp:Addcar' %}"
                  >Add Vehicle</a
                >
                <a class="dropdown-item" href="{% url 'CarsifyApp:MYvehicle' %}"
                  >My Vehicle</a
                >
              </div>
            </div>
          </a>
        </li>
        <li>
          <a href="#"
            ><div class="dropdown show">
              <a
                class="btn dropdown-toggle dropdown-navi"
                href="profile.html"
                role="button"
                id="dropdownMenuLink"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                Profile
              </a>

              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="{% url 'CarsifyApp:Profile' %}"
                  >View Profile</a
                >
                <a
                  class="dropdown-item"
                  href="{% url 'CarsifyApp:Editprofile' %}"
                  >Edit Profile</a
                >
                <a class="dropdown-item" href="{% url 'CarsifyApp:Logout' %}"
                  >Logout</a
                >
              </div>
            </div></a
          >
        </li>
        <li><a href="{% url 'CarsifyApp:Favourites' %}">Favourites</a></li>
        <!-- <li><a href="#">Feedback</a></li> -->
      </div>
      <div class="searchicon">
        <span class="fas fa-search"></span>
      </div>
      <div class="cancelicon">
        <span class="fas fa-times"></span>
      </div>
      <form action="#">
        <input
          type="search"
          class="search-data"
          placeholder="Search"
          required
        />
        <button type="submit" class="fas fa-search"></button>
      </form>
    </nav>
    <div class="container py-3 carousel-details">
      <div class="row">
        <div class="col-lg-8">
          <div
            id="carouselExampleIndicators"
            style="max-height: 65vh"
            class="carousel slide"
            data-ride="carousel"
          >
            <ol class="carousel-indicators">
              <li
                data-target="#carouselExampleIndicators"
                data-slide-to="0"
                class="active"
              ></li>

              {% for i in noimages %}
              <li
                data-target="#carouselExampleIndicators"
                data-slide-to="{{ i }}"
              ></li>
              {% endfor %}
            </ol>

            <div class="carousel-inner" style="height: 65vh">
              <div class="carousel-item active">
                <img class="d-block w-100" src="{{ data.Showimage.url }}" />
              </div>

              {% for img in images %}
              <div class="carousel-item">
                <img class="d-block w-100" src="{{ img.Image.url }}" />
              </div>
              {% endfor %}
            </div>
            <a
              class="carousel-control-prev"
              href="#carouselExampleIndicators"
              role="button"
              data-slide="prev"
            >
              <span
                class="carousel-control-prev-icon"
                aria-hidden="true"
              ></span>
              <span class="sr-only">Previous</span>
            </a>
            <a
              class="carousel-control-next"
              href="#carouselExampleIndicators"
              role="button"
              data-slide="next"
            >
              <span
                class="carousel-control-next-icon"
                aria-hidden="true"
              ></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
        <div class="col-lg-4 py-4 features-details">
          

            <div class="py-3 model">
              <h3>Features</h3>


              {% if fav %}
              <h3>
                
                <a
                  href="{% url 'CarsifyApp:Delete_From_Favourite' data.id %}"
                  title="Add to Favourites"
                  ><i class="fa fa-heart"></i
                ></a>
              </h3>
              {% else %}
              <h3>
                <a
                  href="{% url 'CarsifyApp:Add_to_Favourite' data.id %}"
                  title="Remove from Favourites"
                  ><i class="far fa-heart"></i
                ></a>
              </h3>
              {% endif %}
            </div>

            
          <div class="py-3 model">
            <h5><i class="fas fa-car"> </i> {{ data.Company }}</h5>
            <h5><i class="fa fa-plus"> </i> {{ data.Model.Car_Model_Name }} - {{ data.Car_Varient }} </h5>
          </div>
          <div class="py-3 model">
            <h5>
              <i class="fas fa-calendar-check"></i
              >{{data.Date_of_Manufacturing.year}}
            </h5>
            <h5><i class="fa fa-user"></i>{{data.Owners.Owners}}{{data.Owners}} Party</h5>
          </div>
          <div class="py-3 model">
            <h5><i class="fa fa-map"></i>{{data.Card_Registration_Number}}</h5>
          </div>
          <div class="py-3 model">
            <h5>
              <i class="fa fa-map-marker"></i> {{data.City}} - {{data.Registration_State }}
            </h5>
          </div>
          <div class="py-3 model">
            <h5>
              <i class="fa fa-car"></i> {{data.Fuel_Type}} 
            </h5>
          </div>
          <div class="py-3 model">
            <h5>
              <i class="fa fa-road"></i> {{data.KM}}  KM
            </h5>
          </div>
          <div class="py-3 model">
            <h5><a href="{% url 'CarsifyApp:MailImages' data.id %}"> <i class="fa fa-envelope-open-text"></i> Mail Images </a></h5>
            <h5><a href="{% url 'CarsifyApp:DownloadImages' data.id %}" id="downloadLink" download> <i class="fa fa-download"></i> Save Images </a></h5>
          </div>
          <div class="py-3 model">
            <h4><i class="fas fa-rupee-sign mr-2"></i>{{data.Price}}</h4>
          </div>
        </div>
      </div>
      <div></div>
      <div class="description">
        
        <h3>Know more about my vehicle</h3>
        <br/>
        <p>
          {{data.Discription}}
        </p>
        <div>
          <h3>Contact the Dealer</h3>
          <div class="contact-icons">
            <p>
              <i class="fa fa-user"></i>{{data.user.first_name}}
              {{data.user.last_name}}
            </p>
            <p><i class="fa fa-phone"></i> {{ udata.ContactNo }} </p>
            <p><i class="fas fa-envelope-open-text"></i>{{data.user.email}}</p>
          </div>
        </div>
      </div>
    </div>

    <script>
      const menuBtn = document.querySelector(".menuicon span");
      const searchBtn = document.querySelector(".searchicon");
      const cancelBtn = document.querySelector(".cancelicon");
      const items = document.querySelector(".navitems");
      const form = document.querySelector("form");

      menuBtn.onclick = () => {
        items.classList.add("active");
        menuBtn.classList.add("hide");
        searchBtn.classList.add("hide");
        cancelBtn.classList.add("show");
      };

      cancelBtn.onclick = () => {
        items.classList.remove("active");
        menuBtn.classList.remove("hide");
        searchBtn.classList.remove("hide");
        cancelBtn.classList.remove("show");
        form.classList.remove("active");
        cancelBtn.style.color = "#ff3d00";
      };

      searchBtn.onclick = () => {
        form.classList.add("active");
        searchBtn.classList.add("hide");
        cancelBtn.classList.add("show");
      };
    </script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'assets/javascripts/navigation.js' %}"></script>
  </body>
</html>